# Docker Compose file Reference (https://docs.docker.com/compose/compose-file/)
# online yaml parser http://yaml-online-parser.appspot.com/
version: '3'

#define services
services:
  #App backend service
  app-server:
    #configuration for building docker image for backend service
    build:
      context: SpringBootRestAPI
      dockerfile: Dockerfile
    ports:
      - "8080:8080" #forward esposed port 8080 on container to 8080 on machine
    restart: always
    depends_on:
      - mysql #depends on mysql, start that first
    environment: # Pass environment variables to the service
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/austincleanup?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: springuser2
      SPRING_DATASOURCE_PASSWORD: RedArmyPennePasta1!
    networks: #networks to join (services on the same network can communicate)
      - backend
      - frontend

  #frontend service
  app-client:
    build:
      context: ReactFrontend #use image from specfied directory
      dockerfile: Dockerfile.development
      #args:
      # REACT_APP_API_BASE_URL: http://127.0.0.01:8080/api
    ports:
      - "3000:3000" #map exposed port 80 on container to port 9090 on host machine
    restart: always
    volumes:
      - ./ReactFrontend:/app
      - /app/node_modules

    depends_on:
      - app-server
    networks:
      - backend
      - frontend

  #database services (mySQL)
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    restart: always
    environment:
       MYSQL_DATABASE: austincleanup
       MYSQL_USER: springuser2
       MYSQL_PASSWORD: RedArmyPennePasta1!
       MYSQL_ROOT_PASSWORD: root
    volumes:
       - mysql-data:/var/lib/mysql
    networks:
       - backend

#volumes
volumes:
  mysql-data:

#networks to be created to facilitate communication between containers
networks:
  backend:
  frontend:
