mysql:
  image: mysql
  ports:
    - "3306:3306"
  expose:
    - "3306"
  environment:
    - MYSQL_USER=springuser2
    - MYSQL_PASSWORD=RedArmyPennePasta1!
    - MYSQL_DATABASE=austincleanup
    - MYSQL_ROOT_PASSWORD=root
  volumes:
    - "./conf.d:/etc/mysql/conf.d:ro"
